### PR TITLE
Update documentation.md

### PR DESCRIPTION
**Pull request by capz**
found out what AM means on 3dsbrew

### CODE REVIEW

**Comment by xem** [comment]
thanks :) can you please add me on skype? (my id: maxime.euziere)

**Comment by capz** [comment]
i tried but found 3 different ones :P which one do i need?
screen shot 2014-11-27 at 01 14 48

**Comment by xem** [comment]
sorry, it's the first one. the others have suffixes, they're my job accounts ;)

**Comment by xem** [comment]
@capz so, could we talk a moment ? freel free to add me on skype.

**Pull request merged**
