### PR TITLE
Image tuto and fix for image to bin to work with code in tuto!

### PR DESCRIPTION
**Pull request by MrJPGames**
Apparently the "normal" code used to deal with transparency uses "BGRA"!

### CODE REVIEW

**Comment by xem** [comment]
Hi @MrJPGames ! Thanks for this hard work! Two things:
- I'm not sure: did you tweak the hbmenu functions or did you use them as-is in BGR and ABGR, finally?
- I reorganized all the tutorial today and sadly, this makes you unsynced. Could you please update and resend your pull request at the right spot? Thanks a lot!

Another thing we should do: produce a .c and a .h file with all the handy functions we can find, and make the people use them in the tutorial, so they don't have to copy-paste long and complicated functions somewhere. Whaddayathink?

**Comment by MrJPGames** [comment]
1. Yes this is how this is the functions as present in hbmenu (https://github.com/smealum/3ds_hb_menu/blob/master/source/gfx.c)
2. Where did you reorganize? When I know I will update!
   Probably last thing not a great idea (waste of memory if people don't use them) but including functions for that tutorial (say gfx.c/gfx.h for images) would be a great idea as it makes it easier!

**Comment by MrJPGames** [comment]
Should be able to merge now, took a little bit of work. (Merging didn't go great so it would be nice if you rechecked for any errors (mainly some text was slightly corrupted but I think it's fixed now but still worth checking!))

**Comment by xem** [comment]
thanks! I'll merge it this evening, and I'll take your idea of a separate .c/.h file containing the functions :)

**Comment by xem** [comment]
Also, I'm pretty sure that if a function is not used in a program, it's not compiled and doesn't waste memory.

**Comment by MrJPGames** [comment]
Added gfx.c/gfx.h for image tutorial!
I think the format of files/tutorialsubject/file.extension is probably the best!
So for the image I used files/image/gfx.c
Cheers ;)

**Comment by capz** [comment]
The default makefile doesn't build source files in subfolders of /source/ though...

Also xem is practically correct. Unused code is optimized out of the binary, and so are unused variables. But functions may or may not be. It's easy to check though! Just open the .o file of the source file you've put an unused function in and see if its Name is listed :)

**Comment by MrJPGames** [comment]
Alright, but I that is the location in the repo, not where people will put the files in their projects!
I do still think it would be more organised if the functions are seperate but if this is true they could be in one file.

**Comment by capz** [comment]
Oh that's fine :) and please do split up the source code into separate files as much as sensibly possible!

**Comment by xem** [comment]
I'm merging and taking care of it. Thanks again for the effort!

**Comment by xem** [comment]
Hi guys, I updated the project with a big cleanup of the files and the tutorial. The merge was rather catastrophic and I removed all the mess and rewrote/adapted the image drawing chapter by reusing all the information from the pull request. Next time if there is a merge conflict, don't bother trying to fix it, I'll do it manually. Anyway, you did a very useful work and you're welcome to continue this way (if you don't mind when I do a second pass on the copy). Cheers!

**Pull request merged**
