### PR TITLE
Button Tutorial

### PR DESCRIPTION
**Pull request by MrJPGames**
Ton't should be don't

### CODE REVIEW

**Comment by MrJPGames** [comment]
Added button tutorial!

**Comment by MrJPGames** [comment]
Fixed the "outdatedness" of the file should be alright now ;)

**Comment by xem** [comment]
I don't know who is this @JPcracker but thanks for his merging efforts :p 
And of course thanks to the author. I'll make a few adjustments to the button chapter tomorrow, but the biggest part is here, and it's great.

**Comment by MrJPGames** [comment]
That's me. I don't know but when using github for windows it says JPCracker even though I'm using the same account!

**Pull request merged**
