### PR TITLE
Update functions.c

### PR DESCRIPTION
**Pull request by capz**
reformatted code for better readability

### CODE REVIEW

**Comment by xem** [comment]
thanks @capz !
while we're at it, what do you think of making those functions work with normal coordinates (X=0;Y=0 => top-left corner of the screen).
I guess it wouldn't be too intensive...
something like:

```
gfxDraw(..., x, y){

  // rotate coordinates system
  u32 tmp = x;
  x = 240 - y;
  y = tmp;

  // all the code we have now
  ...
}
```

Maybe it can be done without transforming the coordinates at all, something like:

```
memcpy(&fbAdr[ ((240 - y + xOffset) + (x + j) * fbWidth) * 3 ], &spriteData[ ((xOffset + j) * width) * 3 ], widthDrawn * 3); //copy imagedata into memory
```

cc @MrJPGames

**Comment by capz** [comment]
from Skype, so others can see:
i would personally prefer to wait with writing code until i can actually test what i’ve written, but that should be an easy fix :) even you can write it ^^

**Comment by MrJPGames** [comment]
x = y;
y = x - 240 - width;

I think haven't tested!

**Comment by xem** [comment]
@MrJPGames if you do that, Y will be computed using the new value of X (coming from the line above), not the X you really wanted to use. That's why I used a tmp var.

**Comment by MrJPGames** [comment]
Alright but you forgot to take to width into account (top left of image needs to become top right for it took look like it's being rendered from 0,240 as 0,0)

**Comment by xem** [comment]
you're right :) I'll keep that in mind when I write the function tonight. I may ask your help if you're here on skype

**Comment by MrJPGames** [comment]
Alright, will try to online on skype after 7PM?! 
Though people should know that it doesn't really work like this so we should explain how the 3DS does it by itself, but have them use the function for ease of use!

P.s. extra idea should we include a link to a very basic tutorial on c itself at the beggining for people who haven't used C (or any other programming language?)

**Comment by xem** [comment]
Don't explain the C ourselves but okay for a link

**Comment by capz** [comment]
i like this one :) http://www.cprogramming.com/tutorial.html
and strongly agree that we should focus on tutorials and documentation related exclusively to 3DS homebrew and not try to bother teaching the whole languages, you could make an entire website about that subject alone. Keeping the scope down is a good thing ^_^

**Pull request merged**
